name: 💡 Feature request
description: Suggest an idea for our EcoCommons Notebooks!
# title: " "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an EcoCommons Notebooks 💡 Feature request!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/EcoCommons-Australia-2024-2026/notebooks/issues) to see if a similar feature request already exists.
      options:
        - label: >
            I have searched the EcoCommons Notebooks [issues](https://github.com/EcoCommons-Australia-2024-2026/notebooks/issues) and found no similar feature request.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A short description of your tutorial idea.
      placeholder: |
        What tutorial do you think we should add to EcoCommons Notebooks?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a Pull Request?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/EcoCommons-Australia-2024-2026/notebooks/pulls) (PR) to help improve EcoCommons Notebooks for everyone, especially if you have a good understanding of how to implement a fix or feature.
        See the EcoCommons Notebooks [Contributing Guide](https://github.com/EcoCommons-Australia-2024-2026/notebooks/blob/main/CONTRIBUTING.md) to get started.
      options:
        - label: Yes I'd like to help by submitting a Pull Request!